const data = [
  {
    firstName: "Prakhar",
    lastName: "Pandey",
    email: "prakhar@example.com",
    gender: "Male",
    dob: "19th October 2001",
    country: "India",
    state: "Uttar Pradesh",
    city: "Bareilly",
    zip: "243006",
    areaOfInterest: "Reading",
    password: "Pin@123456",
    profilePictureExtension: null,
    profilePictureFilePath: null,
  },
  {
    firstName: "Pikachu",
    lastName: "Sharma",
    email: "pikachu@example.com",
    gender: "Male",
    dob: "19th October 2001",
    country: "India",
    state: "Uttar Pradesh",
    city: "Bareilly",
    zip: "243006",
    areaOfInterest: "Reading",
    password: "Pin@123456",
    profilePictureExtension: null,
    profilePictureFilePath: null,
  },
  {
    firstName: "Spiderman",
    lastName: "Avenger",
    email: "spider@example.com",
    gender: "Male",
    dob: "19th October 2001",
    country: "India",
    state: "Uttar Pradesh",
    city: "Bareilly",
    zip: "243006",
    areaOfInterest: "Reading",
    password: "Pin@123456",
    profilePictureExtension: null,
    profilePictureFilePath: null,
  },
  {
    firstName: "Shaktiman",
    lastName: "Hero",
    email: "shakti@example.com",
    gender: "Male",
    dob: "19th October 2001",
    country: "India",
    state: "Uttar Pradesh",
    city: "Bareilly",
    zip: "243006",
    areaOfInterest: "Reading",
    password: "Pin@123456",
    profilePictureExtension: null,
    profilePictureFilePath: null,
  },
  {
    firstName: "Chimpanzee",
    lastName: "Ape",
    email: "chimp@example.com",
    gender: "Male",
    dob: "19th October 2001",
    country: "India",
    state: "Uttar Pradesh",
    city: "Bareilly",
    zip: "243006",
    areaOfInterest: "Reading",
    password: "Pin@123456",
    profilePictureExtension: null,
    profilePictureFilePath: null,
  },
];

module.exports = data;
